package LatihanPBO;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class testBola extends javax.swing.JFrame {

    
    int length;
    bola DaftarBola[] = new bola[15];
    int lenght = 0;
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;

    String dbUrl = "Jdbc:mysql://localhost:3306/pbo";
    String login = "root";
    String pwd = null;
    String sql = "Select id,nama,diameter from bola";

    private DefaultTableModel model;
    /**
     * Creates new form testBola
     */
    public testBola() {
        initComponents();
        model = new DefaultTableModel();
        tabel_alfian.setModel(model);
        model.addColumn("ID");
        model.addColumn("Nama");
        model.addColumn("Diameter");

        TableColumn column;
        tabel_alfian.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        column = tabel_alfian.getColumnModel().getColumn(0);
        column.setPreferredWidth(100);
        column = tabel_alfian.getColumnModel().getColumn(1);
        column.setPreferredWidth(200);
        column = tabel_alfian.getColumnModel().getColumn(2);
        column.setPreferredWidth(200);
        
        getData();
    }
    
    
    public void getData() {
        //menghapus isi table tblGaji
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        try {
            //membuat statemen pemanggilan data pada table tblGaji dari database
            Statement stat = (Statement) koneksi.getKoneksi().createStatement();
            String sql = "Select * from bola";
            
            ResultSet res = stat.executeQuery(sql);
            
            
            //penelusuran baris pada tabel tblGaji dari database
            for (int i = 0; i < 15; i++) {
                DaftarBola[i] = new bola();
            }

            int no = 0;
            
            while (res.next()) {
                
                DaftarBola[no].setNama(res.getString("nama"));
                DaftarBola[no].setDiameter(res.getString("diameter"));
                lenght++;
                Object[] obj = new Object[4];
               
                obj[1] = DaftarBola[no].getNama();
                obj[2] = DaftarBola[no].getDiameter()+" cm";

                model.addRow(obj);
                no++;
            }
        } catch (SQLException err) {
            JOptionPane.showMessageDialog(null, err.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_alfian = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        areahasil = new javax.swing.JTextArea();
        luas = new javax.swing.JButton();
        keliling = new javax.swing.JButton();
        volume = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        areafind = new javax.swing.JTextArea();
        cari = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, -1, -1));

        tabel_alfian.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane2.setViewportView(tabel_alfian);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 450, 100));

        areahasil.setColumns(20);
        areahasil.setRows(5);
        jScrollPane1.setViewportView(areahasil);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 470, 160));

        luas.setText("Luas");
        luas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luasActionPerformed(evt);
            }
        });
        jPanel1.add(luas, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        keliling.setText("Keliling");
        keliling.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kelilingActionPerformed(evt);
            }
        });
        jPanel1.add(keliling, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, -1, -1));

        volume.setText("Volume");
        volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volumeActionPerformed(evt);
            }
        });
        jPanel1.add(volume, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        areafind.setColumns(20);
        areafind.setRows(5);
        jScrollPane3.setViewportView(areafind);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 470, 140));

        cari.setText("Find");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel1.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Muhammad Hanif");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 280, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 588));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
            
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
        

        String search = JOptionPane.showInputDialog("Input Karakter");
        areafind.setText("");
        
        int a=0;
        for (int i = 0; i < lenght; i++) {
            if (DaftarBola[i].getId().equalsIgnoreCase(search) || DaftarBola[i].getNama().equalsIgnoreCase(search) || DaftarBola[i].getDiameter().equalsIgnoreCase(search)) {
                
                areafind.append("Nama\t : " + DaftarBola[i].getNama() + "\n");
                areafind.append("Diameter\t : " + DaftarBola[i].getDiameter() + " cm\n");
                areafind.append("------------------------------------\n");
                a=2;
            }
        }
        if (a==0) {
                areafind.setText("Data tidak Ditemukan!!");
            }
    }//GEN-LAST:event_cariActionPerformed

    private void luasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luasActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(JOptionPane.showInputDialog("ID BOLA !"));
            a = a - 1;
            DaftarBola[a].getLuas();

            areahasil.setText(""
                    + "Nama Bola\t : " + DaftarBola[a].getNama() + "\n"
                    + "Jari-jari Bola\t : " + Integer.parseInt(DaftarBola[a].getDiameter()) / 2 + "\n"
                    + "Luas Bola\t : " + DaftarBola[a].luas() + "\n");

    }//GEN-LAST:event_luasActionPerformed

    private void kelilingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kelilingActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(JOptionPane.showInputDialog("ID BOLA !"));
            a = a - 1;
            DaftarBola[a].getLuas();

            areahasil.setText(""
                    + "Nama Bola\t : " + DaftarBola[a].getNama() + "\n"
                    + "Jari-jari Bola\t : " + Integer.parseInt(DaftarBola[a].getDiameter()) / 2 + "\n"
                    + "Keliling\t : " + DaftarBola[a].keliling() + "\n");
    }//GEN-LAST:event_kelilingActionPerformed

    private void volumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumeActionPerformed
        // TODO add your handling code here:
        int a = Integer.parseInt(JOptionPane.showInputDialog("ID BOLA !"));
            a = a - 1;
            DaftarBola[a].getLuas();

            areahasil.setText(""
                    + "Nama Bola\t : " + DaftarBola[a].getNama() + "\n"
                    + "Jari-jari Bola\t : " + Integer.parseInt(DaftarBola[a].getDiameter()) / 2 + " cm\n"
                    + "Volume\t : " + DaftarBola[a].volume() + "\n");
    }//GEN-LAST:event_volumeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(testBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(testBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(testBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(testBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new testBola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areafind;
    private javax.swing.JTextArea areahasil;
    private javax.swing.JButton cari;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton keliling;
    private javax.swing.JButton luas;
    private javax.swing.JTable tabel_alfian;
    private javax.swing.JButton volume;
    // End of variables declaration//GEN-END:variables
}
